import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Image from 'next/image'
import Banner from '@/Components/banner'
import Card from '@/Components/card'
import { fetchCoffeeStores } from '@/lib/coffee-store'
import useTrackLocation from '@/hooks/use-track-location'
import { useEffect } from 'react'


export async function getStaticProps(content) {

  const coffeeStore = await fetchCoffeeStores()
  return {
    props: { coffeeStore }
  };
}

export default function Home(props) {

  const { handleTrackLocation, latLong, locationErrorMsg, isFindingLocation } = useTrackLocation()


  console.log({ latLong, locationErrorMsg, isFindingLocation })

  // useEffect(async () => {
  //   if (latLong) {
  //     try {
  //       const fetchedCoffeeStores = await fetchCoffeeStores(latLong, 30)
  //       console.log("fetchedCoffeeStores", fetchedCoffeeStores)
  //     } catch (error) {
  //       console.log({ error })
  //     }
  //   }
  //   // eslint-disable-next-line react-hooks/exhaustive-deps
  // }, [latLong])

  useEffect(() => {
    (async () => {

      if (latLong) {
        try {
          const fetchedCoffeeStores = await fetchCoffeeStores(latLong, 30)
          console.log("fetchedCoffeeStores", fetchedCoffeeStores)
        } catch (error) {
          console.log({ error })
        }
      }

    })();

  }, [latLong])

  const handleOnBannerBtnClick = () => {
    handleTrackLocation()
  }

  return (
    <>
      <Head>
        <title>Coffee Connoisseur</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <main className={styles.main}>
        <Banner buttonText={isFindingLocation ? "Locating... " : "view store nearby"} handleOnClick={handleOnBannerBtnClick} />
        {locationErrorMsg && <p>something want wrong : {locationErrorMsg}</p>}
        <div className={styles.heroImage}>
          <Image src={"/static/hero-image.png"} width={700} height={400} />
        </div>
        {props?.coffeeStore?.length > 0 && <>
          <h2 className={styles.heading2}>Torono stores</h2>
          <div className={styles.cardLayout}>
            {props.coffeeStore.map((coffeeStore) => {
              return <Card key={coffeeStore.id} name={coffeeStore?.name} ImgUrl={coffeeStore.imgUrl || "https://images.unsplash.com/photo-1498804103079-a6351b050096?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=2468&q=80"} href={`coffee-store/${coffeeStore.id}`} className={styles.card} />

            })}

          </div>
        </>}
      </main>
    </>

  )
}
